### ISSUE TITLE
Compress build urls

### ISSUE THREAD

**Issue by erosson** [erosson/ch2plan#10]

**Comment by Judgy53** [comment]
I did a bit of research and experimenting on that issue and here's what I found :
- Found [hashids](https://github.com/ivanakimov/hashids.js) and its [elm port](https://github.com/pdamoc/elm-hashids). Looked very promising.
- Thought about using an alphabet and splitting the id list in smaller ones. That way, each node is bound to a single character, plus an additional separator '&' each time we loop through the alphabet. Wrote a implementation of the encoding part [here](https://gist.github.com/Judgy53/b754110949d949acc1ae48fed566a306)

Now the results. I selected 309 nodes randomly (thanks multiSelect feature 😄  ) and compared the output length :
- Current method : 1161 characters
- hashids (js version on [codepen](https://codepen.io/ivanakimov/pen/bNmExm)) : 893 characters
- Alphabet + split : 318 characters

It's still very long but that's much better than what we currently have.

**Comment by erosson** [comment]
Thank you!

More possiblities: 

* looks like Path of Exile planners store each node as 2 bytes - constant size means no '&' separator required. about half the size of the current format (about 4 bytes per node - 3 digits and a '&'). https://www.pathofexile.com/forum/view-thread/83305 , https://gist.github.com/tralamazza/c379c350654169de822a
* bitwise: Each node can be either selected or unselected - 0 or 1 - 1 bit. We have about 700 nodes - 700 bits. 1 base64 character = 6 bits. (Can't use all 8 bits in a char because some don't work in urls.) Could store a build in (700 / 6) = 117 base64 characters, regardless of how many nodes are selected. Inefficient for early builds with only a few selected nodes, but tough to beat for later builds.

bitwise and alphabet-split both depend on ch2's node ids staying relatively small. If Fragsworth and friends decide to start using 5-digit nodeids for whatever reason, either approach would have to map their ids to smaller ids to keep sizes reasonable - painful for future updates, especially if node ids change. ch2 devs sound like they're careful about updates that break save compatibility, which likely means node ids won't change - and they're not even using ids we have to map yet. tradeoff's probably worth it.

(maybe this isn't worth the trouble. large build urls look obnoxious but still work fine, and it's kind of nice for humans to be able to understand a build url. I couldn't have done this with a fancy compressed format: https://www.reddit.com/r/ClickerHeroes/comments/8zjsfk/clicker_heroes_2_skill_tree_planner/e2rpfmm/ )

**Comment by Judgy53** [comment]
So many ways to encode a build, I guess it's time to chose, right ?

I personally prefer shorter urls, so would go for bitwise (with some optimizations like only encode up to highest selected id, and make special cases for long series of 1 or 0).
That said, I like the current format for its readability (being able to tell if early or late game without clicking) and its easy manipulation. So I wouldn't mind keeping that way.

What about supporting both and giving the user the choice, with a "Share the build" button for example ?  ( Would be a bit of a hassle to update if the node system change though. ) Or maybe ask the player base on Reddit/Discord what they would prefer, it's for them after all 😄

**Comment by erosson** [comment]
> What about supporting both

The current format will be *readable* forever since urls for it already exist, but *writing* more than one format - absolutely not. Allowing an option confuses new users ("what does this do?"/"why does it matter?"), including anyone who sees the generated urls; it's more places bugs can appear; it's one more thing to test and support; have to find UI space for it somewhere; and there's not enough benefit for all that to be worth it.

I doubt many players have strong opinions here - don't think a poll's worth the trouble.

Thinking through this, I'm leaning toward keeping the current format for now. the bitwise thing would be fun to implement and the small urls are prettier, but I'm not feeling that prettier/smaller beat simple/human-readable/already-working, for now. Can always revisit this if the tradeoffs change later.
