### ISSUE TITLE
select distant nodes, connecting the shortest path in between

### ISSUE THREAD

**Issue by erosson** [erosson/ch2plan#2]
same for deselecting, deselect the disconnected nodes. Like PoB.

**Comment by erosson** [comment]
Got dijkstras working, but it's pretty slow and makes the UI hang. #8 and/or doing it asynchronously ( http://package.elm-lang.org/packages/elm-lang/core/latest/Process ? ) should help.

**Comment by erosson** [comment]
Thanks for testing! Call me picky, but I notice a longer delay, and it's enough to be careful about releasing this. My own worst critic, etc. 

---

A few changes tonight to make this faster: 

* the algorithm doesn't sort the list every time it tries a node - instead, it's faster to iterate and find the smallest without sorting
  * priority queue would be faster, but makes the implementation more complex, so I haven't done it
* dijkstra's re-runs just after the user clicks, instead of onClick (unless they click very quickly), so it's already computed for their next click

This is probably as good as we can reasonably get with dijkstra's. Should be safe to release this - tomorrow, when I'm more awake.

---

Still have doubts, though - PoEPlanner multiselect feels instant, why doesn't mine? They're closed-source, sadly. Maybe there's a better approach than dijkstra's. Imagine precomputing dijkstra's paths for every node - lots of memory required (700ish nodes * 700ish nodes), but I don't think that's *too much*, and it'd be much faster - O(n) where n=num-selected-nodes, as opposed to Dijkstra's scaling on num-nodes. Also, what about A*?

Yosef knows more about graphs than me. I'll talk to him once he's back in town.

**Comment by JourneyOver** [comment]
> PoEPlanner multiselect feels instant, why doesn't mine?

Can't really say why yours doesn't feel instant. Testing speeds of PoEPlanner and this a bit more, the speeds for the multiselect seems to match up at nearly the same speeds (POEPlanner is slightly faster by mere milliseconds (so nothing outrageous)) for at least myself still, but I can't really say how well it'll be for everyone else, since you yourself seem to be getting longer delays.
