### ISSUE TITLE
Import build from save

### ISSUE THREAD

**Issue by Judgy53** [erosson/ch2plan#22]
Importing build from savefile would make sharing builds much easier.

**Comment by erosson** [comment]
...it would? Copy-pasting a link/clicking a link seems easier to me than dealing with file uploads/downloads, and old builds littering my download folder.

Not necessarily opposed to this, but not seeing the benefit.

**Comment by Judgy53** [comment]
Let's say you found a build that works fine in game and you want to share it with others. You currently have to create it on the website manually, making sure you don't forget a node or two. Then you share the link.

I think it would be cool if you could upload your game savefile, The build would be instantly created and the link ready to be shared.

**Comment by erosson** [comment]
Oh - reading ch2's save files, not creating new files from the skill planner! I misunderstood, sorry - this would be nice to have, yeah.

**Comment by erosson** [comment]
I'm not up to doing this whole thing today, but I did write a save decoder:

```
#!/usr/bin/env node
// based on https://ch2.dumbinter.net/
// usage: ./decode-save.js /path/to/save.save
// it's probably in C:\Users\$USERNAME\AppData\Roaming\ClickerHeroes2\Local Store\saves\helpful_adventurer.save
const fs = require('fs')
const zlib = require('zlib')
const amf = require('amf-js')
const {promisify} = require('util')

async function main(path) {
  const rawBuf = await promisify(fs.readFile)(path)
  const amfBuf = await promisify(zlib.inflateRaw)(rawBuf)
  const json = amf.deserialize(amfBuf.buffer)
  console.log(JSON.stringify(Object.keys(json.nodesPurchased)))
}
main(process.argv[process.argv.length-1])
.catch(err => {
  console.error(err)
  process.exit(1)
})
```

tested on node, but browser needs to import zlib and amf-js, which both exist for browser (https://ch2.dumbinter.net/ does it). this would need ports, elm doesn't have file upload or zlib or amf.

**Comment by erosson** [comment]
Releasing this shortly. Also related: #46
