### ISSUE TITLE
I made a calculator for CH, you can get the formula and put in your site too

### ISSUE THREAD

**Issue by QuickBOTS** [erosson/ch2plan#25]
https://docs.google.com/spreadsheets/d/1lkYz1oH1mh5unHEt4WFyq_s_mUsxFBkWC35FZ1d9JQA/edit?usp=sharing

title and thanks

**Comment by erosson** [comment]
Nifty, thanks for sharing!

Stat calculations are already tracked in #3, so I'm closing/moving this.

Stats for each node are tough to extract from the game at the moment. I will not add this without a way to do that, without a way to keep it painlessly updated as the game changes - I refuse to hardcode node stats and play whack-a-bug with every ch2 update.

That might mean the ch2 devs make node-stats easier to parse (very possible with respecs coming, that's what I'm waiting/hoping for); or if that doesn't change, it might mean I automatically parse the tooltip text for each node's stats.

**Comment by QuickBOTS** [comment]
idk if its hard coding wise and hope this might help. each node has uniqueID isnt, for example Cd= normal crit damage and qCd is precision bhaal which worth 3 normal crit damage, as you can see the formula from my sheet. they all just adding "q" for the bigger one.

**Comment by erosson** [comment]
#52 just added exporting builds to spreadsheets. (I'll be adding more calculations to the site itself, but there's no way I can keep up with everything people might want to calculate)

Example: https://ch2.erosson.org#/tsv/0.06-beta/helpfulAdventurer/1&2&3&4&5&6&15&22&23&30&31&37&38&40&48&49&52&53&60&73&74&75&76&79&80&81&85&86&100&103&105&108&114&120&123&124&125&155&200&207&226&227&228&237&262&270&297&324&372&393&403&409&447&448&634&636&643&659&660&661&674&786

Looks like you still update your calculator - it'd be cool if it worked with this! Let me know if I can help.
