### ISSUE TITLE
search box lags and skips input

### ISSUE THREAD

**Issue by erosson** [erosson/ch2plan#31]
seems like it takes the url changes a moment to register, and if I type a character before it registers, that char is overwritten - feeling like the searchbox skips characters unless I type very slowly.

I haven't heard anyone else complain about this, maybe it's linux-only?

**Comment by QuickBOTS** [comment]
it does this on chrome windows too, is updating to url important for the search?

**Comment by erosson** [comment]
Thanks for verifying!

It's important that you can link to a search, but the url change doesn't have to be instant. Fix will likely be to delay the url change until the user stops typing.

**Comment by erosson** [comment]
Biggest problem here was that I needlessly recomputed the slow shortest-path-between-all-nodes code (#2) whenever you typed a letter. Search generates much less lag after that fix, but with fast enough typing it still skipped letters once in a while, so also added the url change delay.
