### ISSUE TITLE
Lag when drag the screen

### ISSUE THREAD

**Issue by QuickBOTS** [erosson/ch2plan#36]
is it just me or what? its like super lag

the more you zoomed out the more it lag when you drag

**Comment by erosson** [comment]
It's not just you - looks like dragging inefficiently recalculates the entire graph every time the mouse moves a single pixel. Definitely possible to optimize this.

**Comment by JourneyOver** [comment]
> looks like dragging inefficiently recalculates the entire graph every time the mouse moves a single pixel. Definitely possible to optimize this.

Guess you optimized it the best you could? as it's still extremely laggy and one reason why I wish that the option to disable zoom/panning wasn't gone..

**Comment by erosson** [comment]
There's still room for improvement. Created #48 to try some things. Also see my answer in b5e17dc40109e1ec877345464c0ebf9a974ed561
