### ISSUE TITLE
Request: Additional search fields that use different colors

### ISSUE THREAD

**Issue by Amadeus99** [erosson/ch2plan#39]
Not sure how useful this would be for others, but I would like to be able to search for two or more different things and have them each circled with different colors.

For example, search for "big clicks" and have them come up with the standard red circles.  And then another search for "increased multiclicks" that would come up with, for example, blue circles.  Why?  Because I want to have as many of the big click damage nodes as I can but fewer of the increased multiclick nodes to lower the energy cost.  By seeing where both are at the same time, it should be easier to figure out what paths I want to take.

This could also be used if someone has two or more different types of nodes they want to try and path more efficiently between.

If you do decide this is worth having, perhaps a plus sign to add another search field or simply add a new search field when something is typed into the currently last search field.  Probably have a maximum number of search fields in either case.  The colors used for each search field could be static for now but eventually add a button next to each search field that shows the current color.  That button could be clicked to open up a color picker.

I'm probably going overboard with this, but I know I would definitely use multiple search fields if they were available.  Up to you if/what you want to implement, if any of this at all.

Thanks.

**Comment by QuickBOTS** [comment]
this +1

**Comment by erosson** [comment]
no objection to this functionality, but the interface is trickier to get right. I'd prefer to start with special syntax on one search field, with no need for interface changes like multiple search fields, to make this possible (but hard to use). if that works well, I can find room for a fancier ui later so it's easier to use.

I took a shot at implementing it that way, but sadly, stumbled into #44.
