### ISSUE TITLE
Being able to have multiple search words at once or ability to favorite specific nodes

### ISSUE THREAD

**Issue by Hazelgnash** [erosson/ch2plan#57]
Not sure what would be the best way to improve this, but the problem I was having when working on my build there are several types of nodes I want to aim for.  Say my primary goal is to pick up every reload node but I want to find a path that also picks up any nearby Huge click node along the way and I also try to get a total of 5x hastened clickstorm nodes as early as possible. But I can only search for one of those things at once. Maybe you could just have multiple separate searches at once and be able to select a custom color for each one. But having all that saved locally instead of just in the build link is another thing I been wanting. Because always having to check my search keyword before linking a build is annoying or having to create a new tinyurl because you missed the search highlight.

**Comment by Judgy53** [comment]
This is already possible and up to 7 search, although the format is really user-friendly : [(big)|(huge)|(multiclick)|(energize)](https://ch2.erosson.org/#/g/0.06-beta/helpfulAdventurer?q=%28big%29%7C%28huge%29%7C%28multiclick%29%7C%28energize%29)

As for saving search locally, I have thought about that before. But linking to a search results can actually be handy, if someone asks where are all reload node and doesn't know about this tool for example.

**Comment by erosson** [comment]
There's now help text for search that explains this. Multicolor highlights are awkward to use, sorry - they were easier/faster to code this way.

Making this easier for users with a separate advanced search page, or multiple show/hideable search fields, or color-pickers for each search field, might be nice someday. Not yet worth the complexity, imo.

I think it's important to be able to link to searches - no plans to remove them from the url, even optionally.

**Comment by Hazelgnash** [comment]
[Oh yeah, this is exactly what I wanted](https://ch2.erosson.org/#/g/0.07-%282%29-beta-PTR/helpfulAdventurer/1&2&3&4&5&6&7&8&12&13&14&15&20&30&31&43&44&45&48&49&54&55&58&61&62&72&74&75&76&82&89&90&92&95&96&97&98&99&101&102&107&111&114&115&117&118&124&290&441&442&449&451&455&457&459&465&466&474&477&480&481&483&488&490&493&494&498&500&507&508&509&517&519&531&533&536&543&544&548&550&551&553&554&555&556&558&560&563&564&565&566&567&571&573&576&577&578&580&581&582&583&584&585&590&594&595&600&606&607&608&609&621&622&626&627&628&646&649&650&655&657?q=%28hastened%20reload%29%7C%28mega%20huger%29%7C%28hastened%20clickstorm%29%7C%28maximum%20energy%29%7C%28maximum%20mana%29)

With local saves I mostly just want something that allows me to save a version of a build and be able to go back to it later without having to manually save the url and paste it into a new tab.  Right now, I just have like 20 bookmarks for different builds but it would be nice to have all those urls saved in my browser cache and able to select which one I want to look at directly on the website rather than trying to navigate my bookmarks.
