### ISSUE TITLE
The search bar is not updating when opening a build.

### ISSUE THREAD

**Issue by Judgy53** [erosson/ch2plan#58]
When loading a build ( for example [(big)|(huge)|(multiclick)|(energize)](https://ch2.erosson.org/#/g/0.06-beta/helpfulAdventurer?q=(big)|(huge)|(multiclick)|(energize)) ), the search bar doesn't fill with the search parameter. It is properly displayed on the graph though.

**Comment by erosson** [comment]
Thanks!
