### ISSUE TITLE
upgrade to elm 0.19

### ISSUE THREAD

**Issue by erosson** [erosson/ch2plan#60]
it's finally out~

https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md

**Comment by erosson** [comment]
pending dependency updates:
  * [ ] [evancz/elm-markdown](https://github.com/evancz/elm-markdown), for the changelog. workaround: parse in js
  * [ ] [NoRedInk/elm-decode-pipeline](https://github.com/NoRedInk/elm-decode-pipeline/), for parsing gamedata json. workaround: use json.decode, without pipelining - I don't think we have anything beyond map8; no big deal
  * [ ] [elm-community/maybe-extra](https://github.com/elm-community/maybe-extra). looks like they have a 0.19 branch, but it's unreleased - `elm install` can't find it, anyway. (list-extra/dict-extra are there.) likely resolved by waiting a bit.
  * [ ] [elm-lang/lazy](https://github.com/elm-lang/lazy) - deprecated?! not good, dijkstra's currently depends on this for reasonable performance through memoization. we'll have to figure out another way to do this.
  * [ ] [elm-community/linear-algebra](https://github.com/elm-community/linear-algebra) and [zaboco/elm-draggable](https://github.com/zaboco/elm-draggable) - used for zooming/panning; not sure how to work around this one - blocker

**Comment by Judgy53** [comment]
Quickly checked if there was any updates :
- [maybe-extra](https://github.com/elm-community/maybe-extra), looks like 0.19 branch has been merged and should now be installable.
- [elm-draggable](https://github.com/zaboco/elm-draggable) has been updated too.
- [elm-live](https://github.com/wking-io/elm-live) now supports 0.19.
- [lazy ](https://github.com/elm-lang/lazy), I've two lazy libs which are entirely written in elm, they might be worth looking at : [eeue56/elm-lazy](https://github.com/eeue56/elm-lazy) and [eeue56/elm-lazy-list](https://github.com/eeue56/elm-lazy-list)

**Comment by erosson** [comment]
Thanks!

Taking another shot at this now. `elm-upgrade` results:

---

SUCCESS! Your project's dependencies and code have been upgraded.
However, your project may not yet compile due to API changes in your
dependencies.

See <https://github.com/elm/compiler/blob/master/upgrade-docs/0.19.md>
and the documentation for your dependencies for more information.

WARNING! 1 of your dependencies have not yet been upgraded to
support Elm 0.19.
  - https://github.com/elm-lang/lazy

Here are some common upgrade steps that you will need to do manually:

- NoRedInk/elm-json-decode-pipeline
  - [ ] Changes uses of Json.Decode.Pipeline.decode to Json.Decode.succeed
- elm/core
  - [ ] Replace uses of toString with String.fromInt, String.fromFloat, or Debug.toString as appropriate
- undefined
  - [ ] Read the new documentation here: https://package.elm-lang.org/packages/elm/time/latest/
  - [ ] Replace uses of Date and Time with Time.Posix
- elm/html
  - [ ] If you used Html.program*, install elm/browser and switch to Browser.element or Browser.document
  - [ ] If you used Html.beginnerProgram, install elm/browser and switch Browser.sandbox
- elm/browser
  - [ ] Change code using Navigation.program* to use Browser.application
  - [ ] Use the Browser.Key passed to your init function in any calls to Browser.Navigation.pushUrl/replaceUrl/back/forward
  - [ ] Change code using Window.* to use Browser.Events.onResize
- elm/url
  - [ ] Changes uses of Navigation.Location to Url.Url
  - [ ] Change code using UrlParser.* to use Url.Parser.*

**Comment by erosson** [comment]
Upgraded. Known caveats:

* failing to parse game data may have some mangled error messages now
* clicking on several nodes really fast might be laggier than before (dijkstra may run twice for fast clicks)
  * a fake Lazy library was small enough to write myself, rather than use someone else's. above is an unavoidable consequence of not having 0.18's laziness side-effects.
* 0.19 adds an `--optimize` flag for smaller/faster js builds. Using it requires removing all `Debug` calls. The goal here was just to get things running in 0.19; punting that optimization to #61.
