### ISSUE TITLE
Better highlights/overlays

### ISSUE THREAD

**Issue by erosson** [erosson/ch2plan#9]
Colors hard to see right now

**Comment by erosson** [comment]
https://www.reddit.com/r/ClickerHeroes/comments/8zjsfk/clicker_heroes_2_skill_tree_planner/e2m5r8m/?context=3

**Comment by erosson** [comment]
even better - icons from the actual game.

Tricky to export, they're fancy transparent animations and my swf decompiler's having trouble, but I did it. Mostly manually - see assets/ch2data/node-img/README

**Comment by Judgy53** [comment]
Wanted to bring to your attention that imagemagick has a fuzz feature that could fix remaining background issues. 10-20% seems to work correctly for "nextNode" one. Would probably want to use a smaller fuzz though for actual nodes though.
PS: I would do it myself but my ffdec crashes halfway through the export :(

**Comment by erosson** [comment]
Thanks, I'll give that a try! #20

Dang, sorry about that. I get occasional crashes with the ffdec gui, but haven't yet had trouble with the command-line export. Learning about flash exporting as I go.
